server:
  port: 81
  servlet:
    context-path: /
spring:
  datasource:
    druid:
      password: Asd123!@#
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.98.219.40:3306/mp
      username: root

mybatis-plus:
  global-config:
    db-config:
      table-prefix: "tbl_"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
